sudo: required
language: generic
matrix:
  include:
    - name: "Gentoo (latest)"
      os: linux
      env: CONTAINER=gentoo
      services: docker
    - name: "Centos 7"
      os: linux
      env: CONTAINER=centos7
      services: docker
    - name: "Centos 8"
      os: linux
      env: CONTAINER=centos8
      services: docker
    - name: "Fedora 28"
      os: linux
      env: CONTAINER=fedora28
      services: docker
    - name: "Fedora 29"
      os: linux
      env: CONTAINER=fedora29
      services: docker
    - name: "Debian Stable"
      os: linux
      env: CONTAINER=debianstable
      services: docker
    - name: "Debian Testing"
      os: linux
      env: CONTAINER=debiantesting
      services: docker
    - name: "Ubuntu 16.04"
      os: linux
      env: CONTAINER=ubuntu1604
      services: docker
    - name: "Ubuntu 18.04"
      os: linux
      env: CONTAINER=ubuntu1804
      services: docker
    - name: "OpenSUSE 15.0"
      os: linux
      env: CONTAINER=opensuse1500
      services: docker
    - name: "Archlinux"
      os: linux
      env: CONTAINER=archlinux
      services: docker
    - name: "macOS 10.13"
      os: osx
      osx_image: xcode9.4
      env: CONTAINER=osx
    - name: "macOS 10.14"
      os: osx
      osx_image: xcode10.3
      env: CONTAINER=osx
install:
  # Build the docker container
  - pushd $TRAVIS_BUILD_DIR
  - if [[ $CONTAINER != "osx" ]]; then docker-compose build test-$CONTAINER ; fi
script:
  - if [[ $CONTAINER != "osx" ]]; then docker-compose run test-$CONTAINER; else bash test/scripts/test_osx.sh ; fi
